#!/bin/bash

sudo apt-get install poppler-utils libspectre-dev libtiff-dev libchm-dev
sudo apt-get install libepub-dev 
cd /tmp/
wget http://download.kde.org/stable/qimageblitz/qimageblitz-0.0.6.tar.bz2
tar -xvf qimageblitz-0.0.6.tar.bz2
cd qimageblitz-0.0.6
mkdir build
cd okular/cmake
sudo cmake -DCMAKE_INSTALL_PREFIX=$KDE_PREFIX -Wno-dev ..
sudo make
sudo make install 
cd /tmp
git clone git://anongit.kde.org/okular
cd okular
mkdir build
cd build
sudo cmake -DCMAKE_INSTALL_PREFIX=/opt/okular
sudo rm /usr/bin/okular
sudo cp /opt/okular/bin/okular /usr/bin
